name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy To Server
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_HOST: ${{ secrets.SSH_HOST }}
          SERVER_USER: ${{ secrets.SSH_USER }}
        run: | 
          echo "$SSH_KEY" > key.pem
          chmod 600 key.pem
          ssh -i key.pem -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST '
          cd /home/ubuntu/crud
          docker-compose down --volumes --remove-orphans
          docker-compose build --no-cache
          docker-compose up -d
          docker-compose ps
          '